### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by brj** [nikolaia/oh-my-fish-config#1]
Hi @nikolaia      
I'm no longer maintaining omf, and would appreciate a ton if you can upgrade to [fisherman](https://github.com/fisherman/fisherman):

* Why? fisherman/fisherman#69 (comment)

Everything, including legacy plugins/themes work great with fisherman, but new content is no longer compat. with oh-my-fish.

**Comment by nikolaia** [comment]
Might check it out, but OMF works fine for me
